### PR TITLE
Supports tags filter for nodes

### PR DESCRIPTION
**Pull request by kompotkot**
## Changes

Nobebalancer support of filter by tag.

## How to test these changes?

Tested locally

### CODE REVIEW

**Comment by kompotkot** [comment]
@bugout-dev check
- [ ] Merge and deploy in prod config https://github.com/bugout-dev/systems/pull/8

**Comment by zomglings** [comment]
I tested locally using the modifications on this branch: https://github.com/bugout-dev/moonstream/pull/747

My config (`~/.nodebalancer/config.json`):

```json
[
  {
    "blockchain": "ethereum",
    "endpoint": "<Infura URL>",
    "tags": ["infura"]
  },
  {
    "blockchain": "polygon",
    "endpoint": "<Infura URL>",
    "tags": ["infura"]
  },
  {
    "blockchain": "polygon",
    "endpoint": "<Alchemy URL>",
    "tags": ["alchemy"]
  }
]
```

When I ran this request, I sometimes got the Infura URL in the `x-node-url` response header and sometimes the Alchemy URL:

```bash
curl -v --request POST "http://127.0.0.1:8544/nb/polygon/jsonrpc?access_id=$NB_CONTROLLER_ACCESS_ID&data_source=blockchain&tags=alchemy" \
    --header 'Content-Type: application/json' \
    --data-raw '{
        "jsonrpc":"2.0",
        "method":"eth_blockNumber",
        "id":1
    }'
```

Am I using the wrong query parameter?

**Comment by zomglings** [comment]
@kompotkot : I think it needs documentation for how to use tags, and I think you can probably also write unit tests for the node selection function.

The unit tests are currently failing. This should be fixed, as well. If necessary, remove tests, but there should be a working test framework.

**Comment by zomglings** [comment]
@kompotkot : My bad. I was using `tags` for query parameter when I should have used `tag`.

This request is working well:

```bash
curl -v --request POST "http://127.0.0.1:8544/nb/polygon/jsonrpc?access_id=$NB_CONTROLLER_ACCESS_ID&data_source=blockchain&tag=alchemy" \
    --header 'Content-Type: application/json' \
    --data-raw '{
        "jsonrpc":"2.0",
        "method":"eth_blockNumber",
        "id":1
    }'
```

**Review by Andrei-Dolgolev — APPROVED** [review]
Looks correct

**Pull request merged**
