### PR TITLE
ABI Defined dashboards

### LINKED ISSUE #321: Per ABI generated dashboards
Phase 1:
1) All request to backend get data for charts with specified page_size of data.
2) On backend if we have more record out of range and page_seze wich request the frontend we put all in humbug journal(need do it as separte task) and provide inside response some type of cursor.

From the frontend perspective we need to provide dashboard experience as a new feature. This will involve building many different charts that have some general similarities. 

We need to have following features to get frontend product out of it: 

- [ ] "Generate dashboard from ABI" UX
- [ ]  Provide "insights UX" which allow user to quickly get from overview in to atomic events list

This assumes that we need following features internally: 

- [x] #345
- [x] #322
- [x] #344
- [x] #356
- [x] #386
- [x] #378
- [x] #394
- [ ] #348
- [ ] Improve stream endpoint pagination (more details on existing solution in #264 )
- [ ] New frontend component "Report insight"
- [x] New frontend component "Delete Dashboard wizard"

### PR DESCRIPTION
**Pull request by peersky**
## Related issues

resolves #321

### CODE REVIEW

**Comment by Andrei-Dolgolev** [comment]
@bugout-dev check
- [ ] Add env var `AWS_S3_SMARTCONTRACTS_ABI_BUCKET`
- [ ] Clean S3 for ABI from test data
- [ ] Add env var `AWS_S3_SMARTCONTRACTS_ABI_PREFIX` = `v1`

**Comment by kompotkot** [comment]
@bugout-dev check
- [x] Add env var `AWS_S3_SMARTCONTRACTS_ABI_PREFIX` = `v1`
- [x] Add env var `AWS_S3_SMARTCONTRACTS_ABI_BUCKET`
- [x] Add env var `AWS_S3_SMARTCONTRACTS_ABI_PREFIX` = `prod`

**Comment by kompotkot** [comment]
Deploy:

Step 1 deploy backend

Required run subscriptions migration wich add abi, s3_path, buket to subscriptions variable abi_hash adding in add abi process .
```
python -m moonstreamapi.admin.cli subscriptions migration -f moonstreamapi/admin/migrations/1_add_abi_backet_and_s3_path.json
```

Required run subscription type polygon was added:
```
python -m moonstreamapi.admin.cli subscriptions subtype ensure-canonical
```

Step 2 deploy mooncrawls
run service.


Step 3 deploy bakend test all on front

**Comment by kompotkot** [comment]
@bugout-dev check
- [ ] Run resources subscription

**Review by kompotkot — APPROVED** [review]
lgtm

**Pull request merged**
