### PR TITLE
Toggle sidebar after link click in mobile view.

### PR DESCRIPTION
**Pull request by kellan-simiotics**
## Changes
Sidebar should close after a link click in mobile view.

## How to test these changes?
Tested locally.

### CODE REVIEW

**Comment by peersky** [comment]
Could you add same behaviour to state of sidebar when `ui.isLoggedIn=true`  (same file L129)

**Comment by kellan-simiotics** [comment]
@peersky Implemented same behavior for logged in mode. Also noticed an issue where changing to a dashboard that has already been opened doesn't change the UI state. This seems to be independent of the sidebar toggle, so I did not address it. I can look into this if it is a priority.

**Comment by peersky** [comment]
Also with sidebar same fix to Subscriptions Api Keys links on bottom of sidebar

**Comment by kellan-simiotics** [comment]
> Also with sidebar same fix to Subscriptions Api Keys links on bottom of sidebar

@peersky Done.

**Review by peersky — APPROVED** [review]
lgtm

**Pull request merged**
