### PR TITLE
Polygon crawlers

### PR DESCRIPTION
**Pull request by kompotkot**
## Changes

Update existing crawlers to work with both Ethereum and Polygon node.
- [x] Update arg parser of crawlers to work with polygon
- [x] ~~Update arg parser of nft to work with polygon~~ (hardcoded Ethereum)
- [x] Update deployment scripts

### CODE REVIEW

**Comment by kompotkot** [comment]
@bugout-dev check
- [ ] Merge PR https://github.com/bugout-dev/moonstream/pull/370

**Comment by kompotkot** [comment]
@bugout-dev check
- [ ] Add env var `MOONSTREAM_NONE_POLYGON_IPC_ADDR`
- [ ] Add env var `MOONSTREAM_NODE_POLYGON_IPC_PORT`

**Comment by kompotkot** [comment]
@bugout-dev check
- [ ] Add env var `MOONSTREAM_NONE_POLYGON_IPC_ADDR`
- [ ] Add env var `MOONSTREAM_NODE_POLYGON_IPC_PORT`

**Review by Andrei-Dolgolev — APPROVED** [review]
Looks correct

**Pull request merged**
